name: Checkstyle

on:
  push:            # run on any branch push
  pull_request:    # run on any PR
  workflow_dispatch:

jobs:
  build:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Env setup
        run: |
          mkdir -p /opt/lib
          wget -q -O /opt/lib/checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.6/checkstyle-10.12.6-all.jar
          cd "${GITHUB_WORKSPACE}"
      - name: Run Checkstyle
        run: |
          exec java -jar /opt/lib/checkstyle.jar "." -c "checkstyle_checks.xml" -f xml > results.xml
      - name: Print Results
        run: echo "$(cat results.xml)"
      - name: Check Results
        run: |
          if grep -q error results.xml; then
            echo "Checkstyle found an error - see Print Results step"
            exit 1
          else
            echo "No errors found!"
          fi
